output "certificate_arn" {
  description = "ARN of the issued ACM PCA certificate"
  value       = aws_acmpca_certificate.aws_acmpca_certificate[0].arn
}

output "certificate_pem" {
  description = "PEM-encoded certificate value"
  value       = aws_acmpca_certificate.aws_acmpca_certificate[0].certificate
}

output "certificate_chain" {
  description = "PEM-encoded certificate chain including intermediates and root"
  value       = aws_acmpca_certificate.aws_acmpca_certificate[0].certificate_chain
  sensitive   = true
}

output "csr_pem" {
  description = "PEM-encoded Certificate Signing Request generated by tls_cert_request"
  value       = try(tls_cert_request.tls_cert_request[0].cert_request_pem, null)
}

output "private_key_pem" {
  description = "PEM-encoded private key used to create the CSR"
  value       = try(tls_private_key.tls_private_key[0].private_key_pem, null)
  sensitive   = true
}