output "arn" {
  description = "ARN assigned by AWS for the provider."
  value       = data.aws_iam_saml_provider.this.arn
}

output "create_date" {
  description = "Creation date of the SAML provider in RFC1123 format, e.g. Mon, 02 Jan 2006 15:04:05 MST."
  value       = data.aws_iam_saml_provider.this.create_date
}

output "name" {
  description = "Name of the provider."
  value       = data.aws_iam_saml_provider.this.name
}

output "saml_metadata_document" {
  description = "The XML document generated by an identity provider that supports SAML 2.0."
  value       = data.aws_iam_saml_provider.this.saml_metadata_document
}

output "tags" {
  description = "Tags attached to the SAML provider."
  value       = data.aws_iam_saml_provider.this.tags
}

output "valid_until" {
  description = "Expiration date and time for the SAML provider in RFC1123 format, e.g. Mon, 02 Jan 2007 15:04:05 MST."
  value       = data.aws_iam_saml_provider.this.valid_until
}