output "job_id" {
  description = "ID of the signing job"
  value       = data.aws_signer_signing_job.this.job_id
}

output "region" {
  description = "AWS region where the signing job is located"
  value       = data.aws_signer_signing_job.this.region
}

output "completed_at" {
  description = "Date and time in RFC3339 format that the signing job was completed"
  value       = data.aws_signer_signing_job.this.completed_at
}

output "created_at" {
  description = "Date and time in RFC3339 format that the signing job was created"
  value       = data.aws_signer_signing_job.this.created_at
}

output "job_invoker" {
  description = "IAM entity that initiated the signing job"
  value       = data.aws_signer_signing_job.this.job_invoker
}

output "job_owner" {
  description = "AWS account ID of the job owner"
  value       = data.aws_signer_signing_job.this.job_owner
}

output "platform_display_name" {
  description = "A human-readable name for the signing platform associated with the signing job"
  value       = data.aws_signer_signing_job.this.platform_display_name
}

output "platform_id" {
  description = "Platform to which your signed code image will be distributed"
  value       = data.aws_signer_signing_job.this.platform_id
}

output "profile_name" {
  description = "Name of the profile that initiated the signing operation"
  value       = data.aws_signer_signing_job.this.profile_name
}

output "profile_version" {
  description = "Version of the signing profile used to initiate the signing job"
  value       = data.aws_signer_signing_job.this.profile_version
}

output "requested_by" {
  description = "IAM principal that requested the signing job"
  value       = data.aws_signer_signing_job.this.requested_by
}

output "revocation_record" {
  description = "Revocation record if the signature generated by the signing job has been revoked"
  value       = data.aws_signer_signing_job.this.revocation_record
}

output "signature_expires_at" {
  description = "The time when the signature of a signing job expires"
  value       = data.aws_signer_signing_job.this.signature_expires_at
}

output "signed_object" {
  description = "Name of the S3 bucket where the signed code image is saved by code signing"
  value       = data.aws_signer_signing_job.this.signed_object
}

output "source" {
  description = "Object that contains the name of your S3 bucket or your raw code"
  value       = data.aws_signer_signing_job.this.source
}

output "status" {
  description = "Status of the signing job"
  value       = data.aws_signer_signing_job.this.status
}

output "status_reason" {
  description = "String value that contains the status reason"
  value       = data.aws_signer_signing_job.this.status_reason
}